channels:
  - coecms
  - conda-forge
  - default

dependencies:
  - affine
  - alsa-lib
  - antlr-python-runtime
  - appdirs
  - asttokens
  - attr
  - attrs
  - babel
  - backcall
  - blosc
  - boost-cpp
  - branca
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - cartopy
  - certifi
  - cf-units
  - cf_xarray
  - cfitsio
  - cftime
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - comm
  - contourpy
  - curl
  - cycler
  - dask-core
  - dbus
  - debugpy
  - decorator
  - esmf
  - esmpy
  - executing
  - expat
  - fiona
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-anaconda
  - fonts-conda-ecosystem
  - fonttools
  - freetype
  - freexl
  - fsspec
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - glib-tools
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - iris
  - jedi
  - jinja2
  - joblib
  - json-c
  - jupyter_client
  - jupyter_core
  - kealib
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libarchive
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcups
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libflac
  - libgcc-ng
  - libgcrypt
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libgpg-error
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - libllvm14
  - libllvm16
  - libnetcdf
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - librttopo
  - libsndfile
  - libsodium
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libsystemd0
  - libtiff
  - libuuid
  - libvorbis
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzip
  - libzlib
  - llvmlite
  - locket
  - lz4-c
  - lzo
  - mapclassify
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mpg123
  - mule
  - munch
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nest-asyncio
  - netcdf-fortran
  - netcdf4
  - networkx
  - nspr
  - nss
  - numba
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - parso
  - partd
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - ply
  - pooch
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pulseaudio-client
  - pure_eval
  - pygments
  - pyparsing
  - pyproj
  - pyqt
  - pyqt5-sip
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python-xxhash
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - rasterio
  - readline
  - regionmask
  - requests
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - shumlib
  - sip
  - six
  - snappy
  - snuggs
  - sparse
  - sqlite
  - stack_data
  - threadpoolctl
  - tiledb
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - traitlets
  - typing_extensions
  - tzcode
  - tzdata
  - udunits2
  - urllib3
  - wcwidth
  - wheel
  - xarray
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xerces-c
  - xesmf
  - xkeyboard-config
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxext
  - xorg-xextproto
  - xorg-xf86vidmodeproto
  - xorg-xproto
  - xxhash
  - xyzservices
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  pip:
    - um-packing
    - um-spiral-search
    - um-utils
