channels:
  - coecms
  - conda-forge
  - default

dependencies:
  - psutil
  - setuptools
  - mule
  - numpy
  - xarray
  - iris
  - cf-units
  - cftime
  - netCDF4
  - scipy
  - lazy_loader
  pip:
    - um-packing
    - um-spiral-search
    - um-utils
