channels:
  - coecms
  - conda-forge
  - default

dependencies:
  - setuptools
  - argparse
  - mule
  - numpy
  - xarray
  - iris
  - datetime
  - cf_units
  - cftime
  - netCDF4
  - scipy
  pip:
    - um-packing
    - um-spiral-search
    - um-utils
