#!/bin/bash
# 
# File to test um2nc.py tool with different files and options. 

fun=/g/data/tm70/dm5220/scripts/amami/amami/modify_ancil.py
PYTHON=/scratch/tm70/dm5220/conda/envs/amami/bin/python
n=0

# TEST 1 
# Ancillary file
echo "================== TEST $n: Ancillary file =================="
file=/g/data/access/projects/access/data/ancil/n48_hadgem1/qrparm.orog
$PYTHON $fun $file test$((n:=n+1)).nc