#!/bin/bash
# 
# File to test um2nc.py tool with different files and options. 

fun=/g/data/tm70/dm5220/scripts/amami/amami/um2nc.py
PYTHON=/scratch/tm70/dm5220/conda/envs/amami/bin/python
n=0

# TEST 1 
# Ancillary file
echo "================== TEST $n: Ancillary file =================="
file=/g/data/access/projects/access/data/ancil/n48_hadgem1/qrparm.orog
$PYTHON $fun $file test$((n:=n+1)).nc

# TEST 2
# Ancillary file with dlat/dlon of one field different from file dlat/dlon
((n=n+1))
echo "=== TEST $n: Ancillary file with different field dlat/dlon ==="
file=/g/data/access/projects/access/data/ancil/n48_hadgem1/qrparm.orog
$PYTHON $fun $file test$((n:=n+1)).nc

# TEST 3
# UM output file without timeseries
((n=n+1))
echo "========= TEST $n: UM output file without timeseries ========="
file=/g/data/tm70/dm5220/ancil/david/access_sample/aiihca.paa1apr
$PYTHON $fun $file test$((n:=n+1)).nc

# TEST 4
# UM output file with timeseries
((n=n+1))
echo "========== TEST $n: UM output file with timeseries =========="
file=/g/data/tm70/dm5220/ancil/david/access_sample/aiihca.daa1210
$PYTHON $fun $file test$((n=n+1)).nc