package:
  name: umami
  version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ..


build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}


requirements:
    host:
        - python >=3.9
        - pip
        - pbr
    run:
        - setuptools
        - mule
        - numpy >=1.17 # >=1.17 Needed for a bug of conda build system with mpi packages
        - xarray
        - iris
        - cf_units
        - cftime
        - netCDF4
        - scipy
