# {% set data = load_setup_py_data() %}
{% set version = load_setup_py_data().get('version')  %}

package:
  name: umami
  version: {{ environ.get('GIT_DESCRIBE_VERSION', version) }}

source:
    path: ..


build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}


requirements:
    host:
        - python >=3.9
        - pip
        - pbr
    run:
        - setuptools
        - numpy >=1.17 # >=1.17 Needed for a bug of conda build system with mpi packages
        - mule
        - xarray
        - iris
        - cf-units
        - cftime
        - netCDF4
        - scipy
